### PR TITLE
Target upgrade + update nuget

### PR DESCRIPTION
**Pull request by gabriel-vanca**
Changed target so that systems stop complaining about not having some ancient version of .Net installed
Also updated nuget packages.

### CODE REVIEW

**Comment by coenm** [comment]
Thanks for your effort to create a PR.

I'm willing to take some time to review the changes. However, I notice the build fails because you changed the `global.json` file.

**Comment by gabriel-vanca** [comment]
Oh, interesting, it's not failing for me in Visual Studio. I did comment it out after forking as it does complain about the SDK version if I leave it uncommented, as I have a newer SDK version installed. I think the test might just be failing because comments aren't supposed to exist in JSON files. I removed it now. That seems to have fixed that problem, but now it's complaining the Windows target version is too new. Feel free to set it to 10.0.22621.0. My builder doesn't have either of these issues :(

**Comment by gabriel-vanca** [comment]
Also, just a quick note about the NULL check at https://github.com/gabriel-vanca/RepoM/commit/589f7b6b9814fb731ada07d4fef46621507228d4

That check should be unnecessary as the object technically cannot be null. Even the IDE is insisting I don't need the check because the object cannot be null. Yet, in at least one instance, that object was indeed null and running Stop() on it was crashing the entire app.

**Comment by gabriel-vanca** [comment]
Fixed the build issues now.

**Comment by coenm** [comment]
I notice you addressed a number of things, 

1. The null check in DefaultRepositoryMonitor
Thank you for finding this. Although I believe the overall problem is the non-thread-safety of the class, this might help. I would have accepted the PR with only this change in a sec.

1. Changing behavior when compiled in Debug (`#if DEBUG`) mainly to disable functionality (`UpdateMenuSize(string resolution, MenuSize size)`), and to use other files for configuration (`appsettings.debug.json`) and storage (` Path.Combine(AppDataPathProvider.AppDataPath, "Repositories.cache.debug");`). I recognize the problem you are trying to solve but I don't like the chosen implementation. I've created an issue (#153) for this problem such that we can discuss how to solve the issue first.

1. Styling
You updated the editorconfig and fixed a number of stylings throughout the code. I'm aware of the inconsistency of the code formatting and styling but this doesn't fix it. It seems as a partial update, and I also don't know if the editorconfig is what I would like. I have created an issue for this (#154) and I willing to discuss some formatting and how to address all code styling issues at once in a separate PR. 

1. Package updating
Some of the used packages in RepoM I can upgrade almost without building and trying but for a few I had some problems with in the past. Therefore, I'm keen on updating packages and I find it 'hard' to accept this PR. Also, the Nerdbank.GitVersion package is defined in a "Directory.Build.props" and should only be updated in that file.

1. Misc
Specifying `SupportedOSPlatformVersion` like in
```
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
  </PropertyGroup>
```

Thanks, I'm not quite sure what this does but I would really like to find out. I've created an issue (#155) to do some research. For now, I don't merge it as I don't know what it means.



Again, thanks for your effort. If you revert all changes except the null check I will gladly accept your PR.

**Comment by gabriel-vanca** [comment]
Thank you for your helpful feedback, Coen. I recognise this PR was a bit of a mess as I was just getting used to the code. I think it's best to close it and I'll open a new one. Just a few notes on what you said:

1. I'll get right on it.
2. I tried to generate a special Debug folder initially, but that generated a myriad of errors. Generating `.debug` files is the only fix I could find after trying for about 90 minutes. Also tried to create a special log file, but that is defined in many places, some of which don't support `#if DEBUG`. It's highly frustrating to debug while I have RepoM installed as well. Best to continue the discussion on #153 though.
3. The editorconfig I suggested is functionally the same as the original, just clarifying some extensions. I'm ok with keeping the original though, especially if you're thinking about using something else. Let's continue that discussion on #154.
4. I'm guessing you had issues with the Material package update. Yes, that requires some changes in App.xaml and MainWindow.xaml to use the new Material 3 Themes. I already have a commit prepared for that, but I'll make it in a separate PR from the rest as it leads to a (slight-ish) visual change as well. I will not update the other packages for now either, albeit I had no issue with them.
5. The default for .NET8 is targeting Windows 7. (https://learn.microsoft.com/en-us/dotnet/standard/frameworks). I think best would be targeting Windows 11 and adding support for 10. I suggested targeting Windows 11 22H2 (10.0.22621) and support for Windows 11 21H2 (10.0.22000) or even Windows 10 20H1 (10.0.19041). I doubt anyone running RepoM will be on older systems than that :) We can continue the conversation at #155 as you suggested and do more research. Or just wait for .NET9 later this year (I think?) and see then.

**Comment by gabriel-vanca** [comment]
See #159

**Pull request closed without merging**
